# Generated by Django 4.2.7 on 2023-11-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFutbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador_partido',
            name='ganar',
            field=models.BooleanField(default=False),
        ),
    ]
