# Generated by Django 4.2.8 on 2023-12-16 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appFutbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
