# Generated by Django 4.2.8 on 2023-12-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFutbol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='n_jugadores',
        ),
        migrations.AlterField(
            model_name='partido',
            name='estilo',
            field=models.CharField(choices=[('5', 'Fútbol sala'), ('7', 'Fútbol 7'), ('11', 'Fútbol 11')], max_length=2),
        ),
    ]
