# Generated by Django 4.2.8 on 2023-12-11 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appFutbol', '0002_remove_partido_n_jugadores_alter_partido_estilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
