# Generated by Django 3.2.23 on 2023-11-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFutbol', '0002_alter_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
