# Generated by Django 3.2.23 on 2023-11-05 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFutbol', '0004_alter_reserva_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_usuario', to='appFutbol.usuario'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='usuarios_jugadores',
            field=models.ManyToManyField(related_name='jugadores_partido', through='appFutbol.Jugador_partido', to='appFutbol.Usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creador_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_post', to='appFutbol.usuario'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='campo_reservado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appFutbol.recinto'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador_reserva', to='appFutbol.usuario'),
        ),
    ]
