# Generated by Django 4.2.11 on 2024-03-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appFutbol", "0005_uploadedfile"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Dueñorecinto",
            new_name="Duenyorecinto",
        ),
        migrations.RenameField(
            model_name="recinto",
            old_name="dueño_recinto",
            new_name="duenyo_recinto",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "administardor"), (2, "cliente"), (3, "duenyorecinto")],
                default=1,
            ),
        ),
    ]
