# Generated by Django 4.2.11 on 2024-03-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appFutbol", "0006_rename_dueñorecinto_duenyorecinto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recinto",
            name="latitud",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recinto",
            name="longitud",
            field=models.IntegerField(default=0),
        ),
    ]
